### ISSUE TITLE
Faucet frontend

### ISSUE THREAD

**Issue by yongenaelf** [AElfProject/aelf-faucet-ui#2]
### Tasks

- [x] Simple design for frontend based on the existing faucet's content
- [x] Error handling
- [x] Add support for **claim-seed** endpoint
- [x] Add support for addresses with or without **ELF_** prefix and **_CHAINID** postfix
- [x] Add support for **claim-nft-seed** endpoint
